/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    classes: Class;
    instructors: Instructor;
    testimonials: Testimonial;
    events: Event;
    faq: Faq;
    offers: Offer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    instructors: InstructorsSelect<false> | InstructorsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    footer: Footer;
    schedule: Schedule;
    homepage: Homepage;
    'contact-info': ContactInfo;
    'analytics-settings': AnalyticsSetting;
    'about-gallery': AboutGallery;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    schedule: ScheduleSelect<false> | ScheduleSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'analytics-settings': AnalyticsSettingsSelect<false> | AnalyticsSettingsSelect<true>;
    'about-gallery': AboutGallerySelect<false> | AboutGallerySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Generowany automatycznie z tytułu. Możesz nadpisać ręcznie.
   */
  slug: string;
  /**
   * Ustawienia SEO dla tej strony. Zostaw puste aby użyć domyślnych wartości.
   */
  seo?: {
    /**
     * Tytuł wyświetlany w wynikach Google (max ~60 znaków).
     */
    metaTitle?: string | null;
    /**
     * Opis wyświetlany w wynikach Google (max ~160 znaków).
     */
    metaDescription?: string | null;
    /**
     * Zdjęcie wyświetlane przy udostępnianiu na Facebooku, Twitterze itp.
     */
    ogImage?: (number | null) | Media;
  };
  layout?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            description?: string | null;
            backgroundImage?: (number | null) | Media;
            primaryCta?: {
              text?: string | null;
              link?: string | null;
            };
            secondaryCta?: {
              text?: string | null;
              link?: string | null;
            };
            socialProof?: {
              googleReviewsText?: string | null;
              partnerLogos?:
                | {
                    logo: number | Media;
                    name?: string | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading?: string | null;
            description?: string | null;
            classes?: (number | Class)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'classesOverview';
          }
        | {
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'benefits';
          }
        | {
            heading?: string | null;
            testimonials?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsSection';
          }
        | {
            heading?: string | null;
            description?: string | null;
            instructors?: (number | Instructor)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'instructorsSection';
          }
        | {
            heading: string;
            description?: string | null;
            primaryButton: {
              text: string;
              link: string;
            };
            secondaryButton?: {
              text?: string | null;
              link?: string | null;
            };
            variant?: ('default' | 'dark' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            heading?: string | null;
            description?: string | null;
            logos?:
              | {
                  logo: number | Media;
                  name?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoList';
          }
        | {
            heading?: string | null;
            address?: string | null;
            phone?: string | null;
            email?: string | null;
            openingHours?:
              | {
                  day: string;
                  hours: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactInfo';
          }
        | {
            heading?: string | null;
            description?: string | null;
            successMessage?: string | null;
            recipientEmail?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            embedUrl: string;
            address?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'map';
          }
        | {
            heading?: string | null;
            faqs?: (number | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqSection';
          }
        | {
            heading?: string | null;
            embedCode?: string | null;
            entries?:
              | {
                  dayOfWeek: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
                  time: string;
                  className?: (number | null) | Class;
                  instructor?: (number | null) | Instructor;
                  location?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'schedule';
          }
        | {
            heading?: string | null;
            variant?: ('upcoming' | 'past' | 'all') | null;
            limit?: number | null;
            manualSelection?: (number | Event)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventsList';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            title?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            columns?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: number;
  title: string;
  /**
   * Generowany automatycznie z nazwy. Możesz nadpisać ręcznie.
   */
  slug: string;
  type: 'krav-maga' | 'karate' | 'tai-chi' | 'individual' | 'asg' | 'power-training' | 'other';
  ageGroup?: ('adults' | 'children' | 'all') | null;
  /**
   * Wyświetlane na liście zajęć i w nagłówku podstrony.
   */
  coverImage?: (number | null) | Media;
  heading: {
    title: string;
    subtitle?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  introduction?: {
    title?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
  };
  highlights?:
    | {
        title: string;
        description?: string | null;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        title: string;
        description?: string | null;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  targetAudience?: {
    forWhoTitle?: string | null;
    forWhoContent?: string | null;
    expectTitle?: string | null;
    expectContent?: string | null;
  };
  redirect?: {
    title?: string | null;
    description?: string | null;
    targetClass?: (number | null) | Class;
    buttonText?: string | null;
  };
  logistics?: {
    intensity?: ('low' | 'medium' | 'medium-high' | 'high') | null;
    /**
     * np. "Długie spodnie sportowe, koszulka, woda"
     */
    whatToBring?: string | null;
  };
  instructor?: (number | null) | Instructor;
  testimonials?: (number | Testimonial)[] | null;
  /**
   * Wybierz inne zajęcia, które chcesz polecić na tej podstronie.
   */
  relatedClasses?: (number | Class)[] | null;
  cta?: {
    heading?: string | null;
    description?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  /**
   * Ustawienia SEO dla tej strony. Zostaw puste aby użyć domyślnych wartości.
   */
  seo?: {
    /**
     * Tytuł wyświetlany w wynikach Google (max ~60 znaków).
     */
    metaTitle?: string | null;
    /**
     * Opis wyświetlany w wynikach Google (max ~160 znaków).
     */
    metaDescription?: string | null;
    /**
     * Zdjęcie wyświetlane przy udostępnianiu na Facebooku, Twitterze itp.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors".
 */
export interface Instructor {
  id: number;
  name: string;
  /**
   * Generowany automatycznie z imienia. Używany w URL /instruktor/[slug].
   */
  slug?: string | null;
  /**
   * Kwadratowe zdjęcie profilowe. Zalecany rozmiar: min. 600×600px.
   */
  photo?: (number | null) | Media;
  /**
   * Wyświetlana pod imieniem, np. "KRAV MAGA / SAMOOBRONA".
   */
  specialization?: string | null;
  classes?: (number | Class)[] | null;
  /**
   * Jedno zdanie wyświetlane na karcie instruktora na stronie głównej. Zostaw puste, aby użyć bio.
   */
  excerpt?: string | null;
  bio?: string | null;
  achievements?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Mniejsza liczba = wyżej na liście. 0 = domyślna kolejność.
   */
  order?: number | null;
  /**
   * Ustawienia SEO dla tej strony. Zostaw puste aby użyć domyślnych wartości.
   */
  seo?: {
    /**
     * Tytuł wyświetlany w wynikach Google (max ~60 znaków).
     */
    metaTitle?: string | null;
    /**
     * Opis wyświetlany w wynikach Google (max ~160 znaków).
     */
    metaDescription?: string | null;
    /**
     * Zdjęcie wyświetlane przy udostępnianiu na Facebooku, Twitterze itp.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  author: string;
  avatar?: (number | null) | Media;
  content: string;
  /**
   * Liczba gwiazdek wyświetlanych przy opinii.
   */
  rating?: number | null;
  relatedClass?: (number | null) | Class;
  /**
   * Wyróżnione opinie pojawiają się na stronie głównej.
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('general' | 'classes' | 'pricing' | 'corporate' | 'registration') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Generowany automatycznie z tytułu. Możesz nadpisać ręcznie.
   */
  slug: string;
  coverImage?: (number | null) | Media;
  startDate: string;
  endDate?: string | null;
  /**
   * Np. „18:00" lub „18:00–20:00". Opcjonalne.
   */
  time?: string | null;
  location?: string | null;
  shortDescription?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * URL do zewnętrznego formularza zapisów lub strony kontaktowej.
   */
  registrationLink?: string | null;
  /**
   * Zaznacz jeśli wydarzenie zostało odwołane.
   */
  cancelled?: boolean | null;
  relatedClasses?: (number | Class)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  /**
   * Generowany automatycznie z nazwy. Możesz nadpisać ręcznie.
   */
  slug: string;
  category?: ('company' | 'schools' | 'workshop' | 'birthday' | 'other') | null;
  /**
   * Ikona wyświetlana na karcie oferty.
   */
  icon?: string | null;
  /**
   * Wyświetlane na liście ofert i jako fallback tła nagłówka.
   */
  coverImage?: (number | null) | Media;
  heading: {
    title: string;
    subtitle?: string | null;
    backgroundImage?: (number | null) | Media;
    /**
     * Przycisk wyświetlany w nagłówku, zazwyczaj prowadzący do kontaktu.
     */
    ctaText?: string | null;
    ctaLink?: string | null;
  };
  /**
   * Zbuduj stronę oferty z bloków. Kolejność bloków = kolejność na stronie.
   */
  layout?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            label?: string | null;
            items?:
              | {
                  icon?: string | null;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'offerCards';
          }
        | {
            label?: string | null;
            title: string;
            content?: string | null;
            bullets?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            variant?: ('dark' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'forWho';
          }
        | {
            heading?: string | null;
            email?: string | null;
            phone?: string | null;
            /**
             * Np. "Rezerwacje z wyprzedzeniem minimum 2 tygodnie."
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactCard';
          }
        | {
            heading: string;
            description?: string | null;
            primaryButton: {
              text: string;
              link: string;
            };
            secondaryButton?: {
              text?: string | null;
              link?: string | null;
            };
            variant?: ('default' | 'dark' | 'accent') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            faqs?: (number | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqSection';
          }
        | {
            title?: string | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            columns?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            heading?: string | null;
            offers: (number | Offer)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'relatedOffers';
          }
        | {
            heading?: string | null;
            variant?: ('upcoming' | 'past' | 'all') | null;
            limit?: number | null;
            manualSelection?: (number | Event)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventsList';
          }
      )[]
    | null;
  /**
   * Ustawienia SEO dla tej strony. Zostaw puste aby użyć domyślnych wartości.
   */
  seo?: {
    /**
     * Tytuł wyświetlany w wynikach Google (max ~60 znaków).
     */
    metaTitle?: string | null;
    /**
     * Opis wyświetlany w wynikach Google (max ~160 znaków).
     */
    metaDescription?: string | null;
    /**
     * Zdjęcie wyświetlane przy udostępnianiu na Facebooku, Twitterze itp.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'classes';
        value: number | Class;
      } | null)
    | ({
        relationTo: 'instructors';
        value: number | Instructor;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              backgroundImage?: T;
              primaryCta?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryCta?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              socialProof?:
                | T
                | {
                    googleReviewsText?: T;
                    partnerLogos?:
                      | T
                      | {
                          logo?: T;
                          name?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        classesOverview?:
          | T
          | {
              heading?: T;
              description?: T;
              classes?: T;
              id?: T;
              blockName?: T;
            };
        benefits?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialsSection?:
          | T
          | {
              heading?: T;
              testimonials?: T;
              id?: T;
              blockName?: T;
            };
        instructorsSection?:
          | T
          | {
              heading?: T;
              description?: T;
              instructors?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoList?:
          | T
          | {
              heading?: T;
              description?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactInfo?:
          | T
          | {
              heading?: T;
              address?: T;
              phone?: T;
              email?: T;
              openingHours?:
                | T
                | {
                    day?: T;
                    hours?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              description?: T;
              successMessage?: T;
              recipientEmail?: T;
              id?: T;
              blockName?: T;
            };
        map?:
          | T
          | {
              embedUrl?: T;
              address?: T;
              id?: T;
              blockName?: T;
            };
        faqSection?:
          | T
          | {
              heading?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        schedule?:
          | T
          | {
              heading?: T;
              embedCode?: T;
              entries?:
                | T
                | {
                    dayOfWeek?: T;
                    time?: T;
                    className?: T;
                    instructor?: T;
                    location?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        eventsList?:
          | T
          | {
              heading?: T;
              variant?: T;
              limit?: T;
              manualSelection?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  ageGroup?: T;
  coverImage?: T;
  heading?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
      };
  introduction?:
    | T
    | {
        title?: T;
        content?: T;
        image?: T;
      };
  highlights?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  targetAudience?:
    | T
    | {
        forWhoTitle?: T;
        forWhoContent?: T;
        expectTitle?: T;
        expectContent?: T;
      };
  redirect?:
    | T
    | {
        title?: T;
        description?: T;
        targetClass?: T;
        buttonText?: T;
      };
  logistics?:
    | T
    | {
        intensity?: T;
        whatToBring?: T;
      };
  instructor?: T;
  testimonials?: T;
  relatedClasses?: T;
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instructors_select".
 */
export interface InstructorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  photo?: T;
  specialization?: T;
  classes?: T;
  excerpt?: T;
  bio?: T;
  achievements?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  author?: T;
  avatar?: T;
  content?: T;
  rating?: T;
  relatedClass?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  startDate?: T;
  endDate?: T;
  time?: T;
  location?: T;
  shortDescription?: T;
  content?: T;
  registrationLink?: T;
  cancelled?: T;
  relatedClasses?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  icon?: T;
  coverImage?: T;
  heading?:
    | T
    | {
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
        ctaText?: T;
        ctaLink?: T;
      };
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        offerCards?:
          | T
          | {
              heading?: T;
              subheading?: T;
              label?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        forWho?:
          | T
          | {
              label?: T;
              title?: T;
              content?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        contactCard?:
          | T
          | {
              heading?: T;
              email?: T;
              phone?: T;
              note?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        faqSection?:
          | T
          | {
              heading?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              columns?: T;
              id?: T;
              blockName?: T;
            };
        relatedOffers?:
          | T
          | {
              heading?: T;
              offers?: T;
              id?: T;
              blockName?: T;
            };
        eventsList?:
          | T
          | {
              heading?: T;
              variant?: T;
              limit?: T;
              manualSelection?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  logo?: (number | null) | Media;
  logoText?: string | null;
  links?:
    | {
        label: string;
        href: string;
        subLinks?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    text?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  description?: string | null;
  columns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Linki do mediów społecznościowych wyświetlane w stopce.
   */
  socialLinks?:
    | {
        platform:
          | 'facebook'
          | 'instagram'
          | 'youtube'
          | 'tiktok'
          | 'linkedin'
          | 'twitter'
          | 'snapchat'
          | 'pinterest'
          | 'whatsapp'
          | 'telegram'
          | 'other';
        url: string;
        /**
         * Nazwa klasy Font Awesome Brands bez prefiksu "fa-", np. "mastodon", "bluesky", "threads". Lista: fontawesome.com/icons?f=brands
         */
        customIcon?: string | null;
        /**
         * Tekst dla czytników ekranowych, np. "Śledź nas na Instagramie".
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  bottomText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule".
 */
export interface Schedule {
  id: number;
  title?: string | null;
  subtitle?: string | null;
  entries?:
    | {
        class: number | Class;
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        /**
         * Format: GG:MM
         */
        startTime: string;
        /**
         * Format: GG:MM
         */
        endTime: string;
        /**
         * Np. "4–6 lat", "7–10 lat", "11–14 lat". Wypełnij dla zajęć dla dzieci i młodzieży (poniżej 18 lat).
         */
        ageRange?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  benefits?: {
    items?:
      | {
          icon: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  classes?: {
    items?:
      | {
          title: string;
          description: string;
          /**
           * Np. /zajecia?filter=children
           */
          href: string;
          /**
           * Używany gdy zdjęcie nie jest dostępne
           */
          color?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    heading?: string | null;
    subheading?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  services?: {
    sectionLabel?: string | null;
    sectionTitle?: string | null;
    columns?: ('2' | '3' | '4') | null;
    cards?:
      | {
          tag: string;
          title: string;
          description: string;
          ctaText?: string | null;
          ctaUrl: string;
          /**
           * Np. #2a5298, #8b0000, #1a6b3c
           */
          color?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  pricing?: {
    sectionLabel?: string | null;
    sectionTitle?: string | null;
    note?: string | null;
    plans?:
      | {
          name: string;
          price: string;
          /**
           * Zostaw puste jeśli nie dotyczy
           */
          period?: string | null;
          features?:
            | {
                text: string;
                id?: string | null;
              }[]
            | null;
          ctaText?: string | null;
          ctaUrl?: string | null;
          featured?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: number;
  address?: string | null;
  /**
   * Link otwierający Google Maps w nowej karcie.
   */
  addressLink?: string | null;
  phone?: string | null;
  email?: string | null;
  hours?: string | null;
  /**
   * URL do osadzenia mapy Google Maps jako iframe na stronie Kontakt.
   */
  mapEmbedUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Konfiguracja integracji z Google Analytics 4. Dane wyświetlają się na dashboardzie panelu admina.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings".
 */
export interface AnalyticsSetting {
  id: number;
  /**
   * Numeryczne ID właściwości GA4, np. 123456789. Znajdziesz je w GA4: Admin → Właściwość → ID właściwości.
   */
  propertyId?: string | null;
  /**
   * Adres email service account z Google Cloud, np. my-account@project.iam.gserviceaccount.com. Service account musi mieć dostęp Viewer do właściwości GA4.
   */
  serviceAccountEmail?: string | null;
  /**
   * Klucz prywatny z pliku JSON service account (pole "private_key"). Zaczyna się od -----BEGIN PRIVATE KEY-----.
   */
  privateKey?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-gallery".
 */
export interface AboutGallery {
  id: number;
  title?: string | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  columns?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  logo?: T;
  logoText?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        subLinks?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        text?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  description?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        customIcon?: T;
        label?: T;
        id?: T;
      };
  bottomText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule_select".
 */
export interface ScheduleSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  entries?:
    | T
    | {
        class?: T;
        day?: T;
        startTime?: T;
        endTime?: T;
        ageRange?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  benefits?:
    | T
    | {
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  classes?:
    | T
    | {
        items?:
          | T
          | {
              title?: T;
              description?: T;
              href?: T;
              color?: T;
              image?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        heading?: T;
        subheading?: T;
        buttonLabel?: T;
        buttonHref?: T;
        backgroundImage?: T;
      };
  services?:
    | T
    | {
        sectionLabel?: T;
        sectionTitle?: T;
        columns?: T;
        cards?:
          | T
          | {
              tag?: T;
              title?: T;
              description?: T;
              ctaText?: T;
              ctaUrl?: T;
              color?: T;
              image?: T;
              id?: T;
            };
      };
  pricing?:
    | T
    | {
        sectionLabel?: T;
        sectionTitle?: T;
        note?: T;
        plans?:
          | T
          | {
              name?: T;
              price?: T;
              period?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ctaText?: T;
              ctaUrl?: T;
              featured?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  address?: T;
  addressLink?: T;
  phone?: T;
  email?: T;
  hours?: T;
  mapEmbedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings_select".
 */
export interface AnalyticsSettingsSelect<T extends boolean = true> {
  propertyId?: T;
  serviceAccountEmail?: T;
  privateKey?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-gallery_select".
 */
export interface AboutGallerySelect<T extends boolean = true> {
  title?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  columns?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}